version: '3.8'

services:
  app:
    build: .
    container_name: rag-agent
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./conversation_histories:/app/conversation_histories
      - ./chroma_db:/app/chroma_db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_PATH=/app/chroma_db
    restart: unless-stopped

  # Opcionalmente, puedes agregar un servicio nginx como proxy inverso
  # nginx:
  #   image: nginx:alpine
  #   container_name: rag-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   restart: unless-stopped 